### ISSUE TITLE
Unable to establish connection to mega service

### ISSUE THREAD

**Issue by totallyrandomuser123** [t3rm1n4l/megacmd#100]
I get this error when running megacmd. How can I fix it?

**Comment by ncw** [comment]
I think this got fixed in go-mega, so I made a new release 0.016 with that in.

Can you give it a go?

https://github.com/t3rm1n4l/megacmd/releases/tag/0.016

**Comment by totallyrandomuser123** [comment]
OK, I will try. Thanks

**Comment by totallyrandomuser123** [comment]
Thanks for the update. It works now, but a program I was trying that uses megacmd and go-mega still doesn't work. It says "Unable to establish connection to mega service Object". What can I do to fix it? Thanks.

**Comment by ncw** [comment]
> Thanks for the update. It works now

Great!

> but a program I was trying that uses megacmd and go-mega still doesn't work. It says "Unable to establish connection to mega service Object". What can I do to fix it? Thanks.

Mega have got really strict about rate limiting so I think you'll just have to wait and try again.

**Comment by totallyrandomuser123** [comment]
I'll try the program again and tell if it's working.

**Comment by totallyrandomuser123** [comment]
Sadly, it still doesn't work. Maybe the program I am using is broken.

**Comment by totallyrandomuser123** [comment]
I guess there is nothing I can do. Thanks for fixing megacmd at least. Thanks for everything. I'll close this issue now.
